version: 0.2
phases:
    pre-build:
      commands:
        - echo "Enter the pre-build phase"
    build:
      commands:
        - echo "Enter the build phase"
        - mvn clean prepare-package war:exploded
    post-build:
       commands:
        - echo "Enter the post-build phase"
        - mv target/deploy ./
    artifacts:
      files:
        - deploy/**/*