version: 0.2
phases:
    pre_build:
      commands:
        - echo "Enter the pre-build phase"
    build:
      commands:
        - echo "Enter the build phase"
        - mvn clean prepare-package war:exploded
    post_build:
       commands:
        - echo "Enter the post-build phase"
        - mv target/deploy ./
    artifacts:
      files:
        - deploy/**/*